---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    pipelinesascode.tekton.dev/task: "[ols-installer, ols-e2e-task]"
  name: ols-integration-tests-pipeline
spec:
  description: |
    This pipeline automates the process of running end-to-end tests for OpenShift Lightspeed
    using a ROSA (Red Hat OpenShift Service on AWS) cluster. The pipeline provisions
    the ROSA cluster, installs the OpenShift Lightspeed operator using the installer, runs the tests, collects artifacts,
    and finally deprovisions the ROSA cluster.
  params:
    - name: SNAPSHOT
      description: 'The JSON string representing the snapshot of the application under test.'
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - name: test-name
      description: 'The name of the test corresponding to a defined Konflux integration test.'
      default: 'ols-rag-content-verification'
    - name: namespace
      description: 'Namespace to run tests in'
      default: 'openshift-lightspeed'
  tasks:
    - name: ols-rag-content-verification
      description: Task to verify rag content contains expected paths
      taskSpec:
        steps:
          - name: get-rag-content-image
            image: registry.redhat.io/openshift4/ose-cli:latest
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
            results:
              - name: rag-content-image
                type: string
                description: "service image from snapshot"
            script: |
              dnf -y install jq
              echo -n "$(jq -r --arg component_name "lightspeed-rag-content" '.components[] | select(.name == $component_name) | .containerImage' <<< "$SNAPSHOT")" > $(step.results.rag-content-image.path)
          - name: run-tests
            env:
              - name: RAG_IMAGE
                value: "$(steps.get-rag-content-image.results.rag-content-image)"
            image: RAG_IMAGE
            script: |
              echo "---------------------------------------------"
              echo "working so far"
